name: Package NuGet

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies ATM
      run: dotnet restore ATM/ATM.sln
    - name: Restore dependencies Payment
      run: dotnet restore Payment/Payment.sln
    - name: Restore dependencies Comportamiento
      run: dotnet restore Comportamiento/Comportamiento.sln

    - name: Run tests ATM
      run: dotnet test ATM/ATM.sln --collect:"XPlat Code Coverage"
    - name: Run tests Payment
      run: dotnet test Payment/Payment.sln --collect:"XPlat Code Coverage"
    - name: Run tests Comportamiento
      run: dotnet test Comportamiento/Comportamiento.sln --collect:"XPlat Code Coverage"

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=sebastianfuentesavalos
          -Dsonar.projectKey=sebastianfuentesavalos_lab-2025-ii-pds-u2-03-cs-sebastianfuentesavalos

    - name: Build NuGet packages
      run: |
        dotnet pack Payment/Payment.Domain/Payment.Domain.csproj -o ./nugets
        dotnet pack ATM/ATM.Domain/ATM.Domain.csproj -o ./nugets
        dotnet pack Comportamiento/Comportamiento.Domain/Comportamiento.Domain.csproj -o ./nugets

    - name: Add GitHub NuGet Source
      run: |
        dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GHTOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Publish NuGet packages
      run: |
        dotnet nuget push ./nugets/*.nupkg --source "github" --skip-duplicate