name: Package NuGet

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore Comportamiento.sln

    - name: Run tests
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1.9
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=sebastianfuentesavalos
          -Dsonar.projectKey=sebastianfuentesavalos_lab-2025-ii-pds-u2-03-cs-sebastianfuentesavalos

    - name: Build NuGet packages
      run: |
        dotnet pack Payment.Domain/Payment.Domain.csproj -o ./nugets
        dotnet pack ATM.Domain/ATM.Domain.csproj -o ./nugets

    - name: Publish NuGet packages
      run: |
        dotnet nuget push ./nugets/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json