name: Release Version

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: |
        dotnet restore Payment/Payment.sln
        dotnet restore ATM/ATM.sln
        dotnet restore Comportamiento/Comportamiento.sln

    - name: Build projects
      run: |
        dotnet build Payment/Payment.Domain/Payment.Domain.csproj
        dotnet build ATM/ATM.Domain/ATM.Domain.csproj
        dotnet build Comportamiento/Comportamiento.Domain/Comportamiento.Domain.csproj

    - name: Create NuGet packages
      run: |
        dotnet pack Payment/Payment.Domain/Payment.Domain.csproj -o ./nugets
        dotnet pack ATM/ATM.Domain/ATM.Domain.csproj -o ./nugets
        dotnet pack Comportamiento/Comportamiento.Domain/Comportamiento.Domain.csproj -o ./nugets

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./nugets
        asset_name: nugets
        asset_content_type: application/zip